language: clojure
sudo: required
# lein:
# - 2.6.1
# - 2.8.3 
# jdk:
# - oraclejdk8
# - openjdk9
# - openjdk11
jobs:
    include:
        - jdk: oraclejdk8
          lein: 2.6.1
          env: JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
        - jdk: openjdk9
          lein: 2.8.3
        - jdk: openjdk11
          lein: 2.8.3

before_script:
- ls /usr/lib/jvm/ 
#export PATH=$JAVA_HOME/bin:$PATH
- "javac -version"
- "sudo docker rm -vf aerospike || true"
- "sudo docker run -d --name aerospike -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 aerospike"
after_script:
  - bash -ex test/coveralls.sh
script: lein test
notifications:
  recipients:
    - ido@appsflyer.com
