dist: xenial
sudo: required
language: clojure
lein: lein
before_script:
- "sudo docker rm -vf aerospike || true"
- "sudo docker run -d --name aerospike -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 aerospike"
after_script:
  - bash -ex test/coveralls.sh
script: lein do clean, test :all
notifications:
  recipients:
  - ido@appsflyer.com
