language: clojure
sudo: required
# lein:
# - 2.6.1
# - 2.8.3 
# jdk:
# - oraclejdk8
# - openjdk9
# - openjdk11
jobs:
    include:
        - jdk: openjdk8
          lein: 2.6.1
          before_script:
              - jdk_switcher  use openjdk8
        - jdk: openjdk11
          lein: 2.8.3
          before_script:
              - jdk_switcher  use openjdk8

before_script:
- "javac -version"
- "sudo docker rm -vf aerospike || true"
- "sudo docker run -d --name aerospike -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 aerospike"
after_script:
  - bash -ex test/coveralls.sh
script: lein test
notifications:
  recipients:
    - ido@appsflyer.com
