language: clojure
sudo: required
lein: 2.6.1 # version 2 and up
jdk:
- oraclejdk8
before_script:
- "sudo docker rm -vf aerospike || true"
- "sudo docker run -d --name aerospike -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 aerospike"
script: lein test
notifications:
  recipients:
    - ido@appsflyer.com
